sudo: false
language: android
jdk:
  - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - extra-android-m2repository
    - build-tools-30.0.2
    - android-30
    
before_install:
 - chmod +x gradlew

script:
  - ./gradlew assembleFreeDebug
